languageCode = "en-us"

baseURL = "https://tekiomo.com/"
title = "テキオモの部屋"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "適当な思いつきで書いています"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "tekiomo"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006/01/02"
listDateFormat = "2006/01/02"
archiveDateFormat = "01/02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = []
homeaage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[sidebar_menu]
title = "kani"
mirror = "foo"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = " | "

[params.social]
codepen = ""
email = ""
facebook = ""
github = "tekiomo"
gitlab = "tekiomo"
instagram = ""
linkedin = ""
twitter = "tekiomo"
telegram = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "tekiomo"
repository = "tekiomo.github.io"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"


[[menu.sidebar]]
name = "Top"
weight = -10
identifier = "Top"
url = "/"

[[menu.sidebar]]
name = "blog"
weight = -10
identifier = "Blogs"
url = "/blog"

[[menu.sidebar]]
name = "about"
weight = -10
identifier = "About"
url = "/about"

# [[menu.main]]
# name = "Top"
# weight = -10
# identifier = "Top"
# url = "/"
# 
# [[menu.main]]
# name = "blog"
# weight = -10
# identifier = "Blogs"
# url = "/blog"
# 
# [[menu.main]]
# name = "about"
# weight = -10
# identifier = "About"
# url = "/about"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "ja"
languageName = "Japanese"
weight = 1
